# 数据库的基本配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: hsp
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&serverTimezone=GMT%2B8

  # JPA配置
  jpa:
    database: mysql
    database-platform:

    # 是否在控制台打印SQL
    show-sql: true

    # 每次启动项目时，数据库初始化策略
    # ddl-auto:create----每次运行该程序，没有表格会新建表格，表内有数据会清空
    # ddl-auto:create-drop----每次程序结束的时候会清空表
    # ddl-auto:update----每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
    # ddl-auto:validate----运行程序会校验数据与数据库的字段类型是否相同，不同会报错
    hibernate:
      ddl-auto: update

    # 指定默认的存储引擎为InnoDB，默认情况下，自动创建表的时候会使用 MyISAM 做表的引擎，
    # 如果配置了数据库方言为 MySQL57Dialect，则使用 InnoDB 做表的引擎。
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
